// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQkHyoA62FMqjgxXErYwp2xwCO7sf9kfQ',
    appId: '1:926115863195:web:40cb91764bbb338f7cc43e',
    messagingSenderId: '926115863195',
    projectId: 'between-8456d',
    authDomain: 'between-8456d.firebaseapp.com',
    storageBucket: 'between-8456d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVQzH_QLwnrqxZPLn3_wKoAXAKGEA68ls',
    appId: '1:926115863195:android:2bed573efde7e08e7cc43e',
    messagingSenderId: '926115863195',
    projectId: 'between-8456d',
    storageBucket: 'between-8456d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD59OBo4jL0aimWvEOfgpsJMOBltnbqhV4',
    appId: '1:926115863195:ios:110c2e54fafd6c687cc43e',
    messagingSenderId: '926115863195',
    projectId: 'between-8456d',
    storageBucket: 'between-8456d.firebasestorage.app',
    iosBundleId: 'com.example.between',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD59OBo4jL0aimWvEOfgpsJMOBltnbqhV4',
    appId: '1:926115863195:ios:110c2e54fafd6c687cc43e',
    messagingSenderId: '926115863195',
    projectId: 'between-8456d',
    storageBucket: 'between-8456d.firebasestorage.app',
    iosBundleId: 'com.example.between',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQkHyoA62FMqjgxXErYwp2xwCO7sf9kfQ',
    appId: '1:926115863195:web:2adc4c17210138897cc43e',
    messagingSenderId: '926115863195',
    projectId: 'between-8456d',
    authDomain: 'between-8456d.firebaseapp.com',
    storageBucket: 'between-8456d.firebasestorage.app',
  );
}
